name: 'JiraTaskSync'
description: 'Sync GITHUB Issues with JIRA Tasks (or Subtasks)'
inputs:
  JIRA_BASEURL:
    description: 'hostname to connect to Jira (do not add https://)'
    required: true
    default: 'localhost'
  JIRA_USEREMAIL:
    description: 'user email/login address to use the token of'
    required: true
    default: 'BLANK'
  JIRA_APITOKEN:
    description: 'token to use to connect to JIRA'
    required: true
    default: 'http://localhost'
  JIRA_PROJECTKEY:
    description: 'the key (prefix) used by JIRA for the project'
    required: true
    default: 'BLA'
  JIRA_ISSUETYPE_NAME:
    description: 'the JIRA issue type to use in JIRA to track the GITHUB Issues'
    required: true
    default: 'Subtask'
  SUBTASK_MODE:
    description: 'Should we attach in JIRA to the labelled story/task as a subtask of the specified JIRA_ISSUETYPE_NAME or replace the story/task itself with GITHUB data'
    required: true
    default: 'true'

outputs: # output will be available to future step
  status:
    description: 'The status of the sync'
  time:
    description: 'when was the sync finished'

runs:
  using: 'node12'
  main: 'dist/index.js'
