name: 'JiraTaskSync'
description: 'Sync GITHUB Issues with JIRA Tasks (or Subtasks)'
inputs:
  JIRA_BASEURL:
    description: 'hostname to connect to Jira (do not add https://)'
    required: true
    default: 'localhost'
  JIRA_USEREMAIL:
    description: 'user email/login address to use the token of'
    required: true
    default: 'BLANK'
  JIRA_APITOKEN:
    description: 'token to use to connect to JIRA'
    required: true
    default: 'http://localhost'
  JIRA_PROJECTKEY:
    description: 'the key (prefix) used by JIRA for the project'
    required: true
    default: 'BLA'
  JIRA_ISSUETYPE_NAME:
    description: 'the JIRA issue type to use in JIRA to track the GITHUB Issues'
    required: true
    default: 'Subtask'
  JIRA_STATE_INPROGRESS:
    description: 'the JIRA transition name equivalent to GITHUB assigned (In Progress)'
    required: true
    default: 'In Progress'
  JIRA_STATE_DONE:
    description: 'the JIRA transition name equivalent to GITHUB closed (Done)'
    required: true
    default: 'Done'
  JIRA_STATE_TODO:
    description: 'the JIRA transition name in JIRA equivalent to GITHUB open/reopened (To Do)'
    required: true
    default: 'To Do'
  SUBTASK_MODE:
    description: 'Should we attach in JIRA to the labelled story/task as a subtask of the specified JIRA_ISSUETYPE_NAME or replace the story/task itself with GITHUB data'
    required: true
    default: true
  ASSIGNEE_PUSH:
    description: 'Whether we want to extract and push the first assignee email as found in GITHUB into the assignee field in JIRA'
    required: true
    default: false
  DEBUG_MODE:
    description: 'Should log as many info as possible'
    required: true
    default: false

outputs: # output will be available to future step
  status:
    description: 'The status of the sync'
  time:
    description: 'when was the sync finished'

runs:
  using: 'node12'
  main: 'dist/index.js'
