name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  jira-prefix:
    description: 'the prefix used by JIRA for the project to attache the stories to'
    required: true
    default: 'BIP'
outputs: # output will be available to future steps
  status:
    description: 'The status of the sync'
  time:
    description: 'when was the sync finished'
runs:
  using: 'node12'
  main: 'dist/index.js'
