name: Sync with JIRA

on:
  issues:
#    types: [opened, edited, closed, reopened, assigned, deleted, labeled, unlabeled]
#  label:
#  issue_comment:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: b-yond-infinite-network/ga-sync-issues-to-jira@master
        with:
          JIRA_PROJECTKEY:  OS
          JIRA_BASEURL:     ${{ secrets.JIRA_BASEURL }}
          JIRA_USEREMAIL:   ${{ secrets.JIRA_USEREMAIL }}
          JIRA_APITOKEN:    ${{ secrets.JIRA_APITOKEN }}
          DEBUG_MODE:       true
          ASSIGNEE_PUSH:    test, somethingelse
