name: test-issuetrigger

on:
  issues:
    types: [opened, edited, closed, reopened, deleted, labeled, unlabeled]
#  label:
  issue_comment:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: b-yond-infinite-network/sync-jira-subtask-to-gh-issues-action@master
        with:
          JIRA_PROJECTKEY:  TEST
          JIRA_BASEURL:     ${{ secrets.JIRA_BASEURL }}
          JIRA_USEREMAIL:   ${{ secrets.JIRA_USEREMAIL }}
          JIRA_APITOKEN:    ${{ secrets.JIRA_APITOKEN }}
